# based on https://github.com/mamba-org/provision-with-micromamba
name: build
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test:
    runs-on: ubuntu-22.04
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: bicycle-steer-control-paper.yml
          environment-name: bicycle-steer-control-paper
          extra-specs: |
            python="3.10"
      - name: Install LaTeX
        run: sudo apt-get install -y texlive
      - name: Install BicycleParameters master
        shell: bash -l {0}
        run: |
          git clone https://github.com/moorepants/BicycleParameters.git
          cd BicycleParameters
          python setup.py develop
          cd -
      - name: run tests
        shell: bash -l {0}
        run: |
          micromamba info
          micromamba list
          make
          make paper.html
          mkdir output/
          mv paper.pdf output/
          mv paper.html output/index.html
          mv figures/ output/figures/
      - name: Deploy the website
        shell: bash -l {0}
        if: ${{ github.event_name == 'push' }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email moorepants@users.noreply.github.com
          git remote add deploy "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/moorepants/bicycle-steer-control-paper.git"
          ghp-import --no-jekyll --no-history -r deploy -m "Updated via Github Actions [skip ci]" -p output
